nav:
  - Home: README.md
  - 关于Wiki: about-wiki.md
  - 学生优惠:
      - 主要: 01-student-discounts/student-discounts.md
      - 其他:
          - 网易云音乐: 01-student-discounts/others/netease.md
  - 搜索引擎:
      - 主要: 02-search-platforms/search-platforms.md
  - 工具:
      - 效率软件: 03-tools/tools.md
      - Android:
          - 加密通讯: 03-tools/Android/加密通讯.md
      - 网络安全:
          - 双重身份验证: 03-tools/cyber security/Authenticator.md
          - 密码管理: 03-tools/cyber security/password_manage1.md
      - 奇技淫巧:
          - 校园跑: 03-tools/qi-ji-yin-qiao/campus-running.md
          - 刷课: 03-tools/qi-ji-yin-qiao/pointless-courses.md
  - 学习:
      - 考试和竞赛: 04-study/study.md
  - 生活:
      - 生活实用小技巧: 05-common-sense-of-life/common-sense-of-life.md
  - 就业:
      - 企业文化: 06-recruit-exercitation/recruit-exercitation.md

site_name: AcWiki 大学生的百科全书
site_url: https://acwiki.pages.dev # 预览站点链接，合并成功后需要切换为主仓库链接
site_description: 属于大学生群体的真·青年大学习
repo_name: AcWiki
repo_url: https://github.com/Ac-Wiki/AcWiKi
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 <a href="https://github.com/Ac-Wiki/AcWiKi/" target="_blank">AcWiki</a>

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo_clear.png
  features:
    - navigation.footer
    - content.action.edit # source edit
    - content.action.view # source view
    - navigation.instant # Instant navigation
    #- navigation.tabs 后续可考虑启用
    #- navigation.tabs.sticky
    - toc.follow # Follow TOC
    - navigation.top # Top navigation
  palette:
    # match system theme color
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/AcWiki
      name: Telegram 频道
    - icon: simple/telegram
      link: https://t.me/AcFourm
      name: Telegram 群组

extra_javascript:
  - js/extra.js

markdown_extensions:
  - attr_list
  - admonition #强调块
  - footnotes #脚注
  - md_in_html #支持在 html 中使用 markdown 语法
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.keys

plugins:
  - search
  - git-revision-date-localized: # commit/Modify date
      timezone: Asia/Shanghai
      enable_creation_date: true
  - git-authors: # git authors
      show_email_address: false
  - glightbox: # lightbox
      touchNavigation: true
      loop: true
      effect: none
      slide_effect: fade
      width: auto
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: false
      manual: false
